#
# Example app config file which works with Docker
#
# Unless you modify the docker-compose.yml or Dockerfile, you shouldn't
# need to change these values.
#

[general]
bind_address = "0.0.0.0:3000"

[frontend]
enabled = true
title = "Alexandrie"
description = "An alternative crate registry for Cargo, the Rust package manager."

[frontend.sessions]
cookie_name = "alexandrie.sid"
secret = "YOU_REALLY_SHOULD_CHANGE_THIS_BEFORE_DEPLOYING"

[frontend.assets]
path = "assets"

[frontend.templates]
path = "templates"

[frontend.auth]
origin = "http://localhost:3000"

[frontend.auth.local]
enabled = true
allow_registration = true

[database]
url = "postgresql://root:root@postgresqldb:5432/alexandrie"

[index]
type = "command-line"
path = "appdata/crate-index"

[storage]
type = "disk"
path = "appdata/crate-storage"

[syntect.syntaxes]
type = "dump"
path = "syntect/dumps/syntaxes.dump"

[syntect.themes]
type = "dump"
path = "syntect/dumps/themes.dump"
theme_name = "frontier-contrast"
